- name: Copy stackrc and tripleo-undercloud-password to stack home dir
  shell: "cp /root/{{ item }} /home/stack/{{ item }}"
  with_items:
    - tripleo-undercloud-passwords
    - stackrc

- name: Chown copied files
  shell: "chown stack:stack /home/stack/{{ item }}"
  with_items:
    - tripleo-undercloud-passwords
    - stackrc

- name: Update neutron ports quota
  shell: >
    source /home/stack/stackrc;
    neutron quota-update --port -1

# Workarounds for bug #1246525
- name: Check if HAproxy is installed on the undercloud
  stat:
    path=/etc/haproxy/haproxy.cfg
  register: haproxy_config
   
- name: Disable HAproxy check in config file
  replace:
    dest=/etc/haproxy/haproxy.cfg
    regexp='(listen ironic\n.*\n.*)\n.*option h    ttpchk GET \/'
    replace='\1'
  when: haproxy_config.stat.exists

- name: Restart HAproxy service
  shell: systemctl restart haproxy
  when: haproxy_config.stat.exists
