# The following tasks are workaround for the bug: https://bugzilla.redhat.com/show_bug.cgi?id=1246641
# ---------------------------------------------------------------------------------------------------
- name: Get overcloud nodes IDs
  shell: >
    source /home/stack/stackrc;
    ironic node-list | grep 'None' | awk '{ print $2; }'
  register: overcloud_nodes_ids

- name: Power off overcloud nodes
  shell: >
    source /home/stack/stackrc;
    export MAINTENANCE_STATUS=$(ironic node-show {{ item }} | grep 'maintenance ');
    if [[ $MAINTENANCE_STATUS != *"False"* ]]; then
        ironic node-set-maintenance {{ item }} false;
    fi;
    ironic node-set-power-state {{ item }} off;
    sleep 60;
    export LAST_ERROR=$(ironic node-show {{ item }} | grep 'last_error ');
    export TARGET=$(ironic node-show {{ item }} | grep 'target_power_state');
    if [[ $LAST_ERROR != *"None"* ]]; then
        ironic node-set-power-state {{ item }} off;
        sleep 60;
    fi;
    ironic node-show  {{ item }} | grep ' power_state'
  register: node_power_status
  retries: 5
  delay: 60
  until: node_power_status.stdout.find("power off" ) != -1
  ignore_errors: true
  with_items: overcloud_nodes_ids.stdout_lines
