- name: Wait for at least one node to be available
  shell: >
    source /home/stack/stackrc;
    nova hypervisor-stats
  register: nodes
  until: nodes.stdout.find("count                | 0") == -1
  retries: 10
  delay: 10

- name: Set TripleO enviornment files
  become: yes
  copy:
    src="{{ item }}"
    dest="/home/stack/user_templates/{{ item }}"
  with_items:
    - 'network-environment.yaml'
    - 'compute.yaml'
    - 'controller.yaml'

- name: Create overcloud deploy script
  template:
    src="deploy_overcloud.j2"
    dest="/home/stack/deploy_overcloud.sh"
    mode=0755

- name: Deploy Overcloud
  shell: >
    source /home/stack/stackrc;
    bash /home/stack/deploy_overcloud.sh &> overcloud_deployment.log
  register: overcloud_deployment_result
  failed_when: overcloud_deployment_result.rc != 0
