# The following four tasks are workarounds for the bug: https://bugzilla.redhat.com/show_bug.cgi?id=1313907
# ------------------------------------------------------------------------------------------------------
- name: Add pxe_ssh driver to Ironic configuration
  become: yes
  become_method: sudo
  lineinfile:
    backup=true
    backrefs=true
    dest='/etc/ironic/ironic.conf'
    regexp='^(enabled_drivers=(?:(?!pxe_ssh).)*)$'
    line='\1,pxe_ssh'

- name: Allow Ironic to control the power state
  become: yes
  become_method: sudo
  shell: sed -i 's/force_power_state_during_sync=False/force_power_state_during_sync=True/g' /etc/ironic/ironic.conf

- name: Restart the Ironic conductor service
  become: yes
  become_method: sudo
  service:
    name=openstack-ironic-conductor
    state=restarted

- name: Ensure the pxe_ssh driver is enabled
  shell: >
    source /home/stack/stackrc;
    ironic driver-list;
  register: drivers
  until: drivers.stdout.find("pxe_ssh") > -1
  retries: 100
  delay: 3

# Node registeration
# -----------------
- name: Register overcloud nodes
  shell: >
    source /home/stack/stackrc;
    openstack baremetal import --json instackenv.json;
  register: register_nodes_result
  retries: 10
  delay: 10
  until: register_nodes_result.rc == 0

- name: Assign the kernel and ramdisk images to the overcloud nodes
  shell: >
    source /home/stack/stackrc;
    openstack baremetal configure boot
  register: kernel_assign_result
  retries: 10
  delay: 10
  until: kernel_assign_result.rc == 0
