# Node registeration
# -----------------
- name: Register overcloud nodes
  shell: >
    source /home/stack/stackrc;
    openstack baremetal import --json instackenv.json;
  register: register_nodes_result
  retries: 10
  delay: 10
  until: register_nodes_result.rc == 0

- name: Get overcloud nodes IDs
  shell: >
    source /home/stack/stackrc;
    ironic node-list | grep 'None' | awk '{ print $2; }'
  register: overcloud_nodes_ids

- name: Assign the kernel and ramdisk images to the overcloud nodes
  shell: >
    source /home/stack/stackrc;
    openstack baremetal configure boot
  register: configure_boot
  retries: 10
  delay: 10
  until: configure_boot.rc == 0
