- name: Create overcloud_images directory
  file:
    path=/home/stack/overcloud_images
    state=directory

- include: "{{ image_action | default('import') }}.yml"

- name: Upload images to Glance
  shell: >
    source /home/stack/stackrc;
    openstack overcloud image upload
  args:
    chdir: "/home/stack/overcloud_images"
