- name: Create overcloud_images directory
  file:
    path=/home/stack/overcloud_images
    state=directory

- include: "{{ image_action | default('rpm') }}.yml"

- name: Upload images to Glance
  shell: >
    source /home/stack/stackrc;
    openstack overcloud image upload --image-path /home/stack/overcloud_images/
