- name: Create overcloud_images directory
  file:
    path=/home/stack/overcloud_images
    state=directory

- name: Install libguestfs-tools to modify the images
  yum:
    name=libguestfs-tools
    state=present

- name: Obtain overcloud images
  shell: "wget --quiet -c -O /home/stack/overcloud_images/{{ item }}.tar http://rhos-release.virt.bos.redhat.com/puddle-images/latest-7.0-images/{{ item }}.tar"
  args:
    chdir: "/home/stack/overcloud_images"
  with_items:
    - 'deploy-ramdisk-ironic'
    - 'discovery-ramdisk'
    - 'overcloud-full'

- name: Extract tar files
  shell: "tar -xvf {{ item }}.tar"
  args:
    chdir: "/home/stack/overcloud_images"
  with_items:
    - 'deploy-ramdisk-ironic'
    - 'discovery-ramdisk'
    - 'overcloud-full'
    
- name: Inject patches to overcloud full image
  shell: "virt-copy-in /patched_rpms / -a overcloud-full.qcow2; virt-customize --copy-in /home/cloud-user/patched_rpms:/home/cloud-user/patched_rpms -a overcloud-full.qcow2"
  args:
    chdir: "/home/stack/overcloud_images"

- name: Upload images to Glance
  shell: >
    source /home/stack/stackrc;
    openstack overcloud image upload 
  args:
    chdir: "/home/stack/overcloud_images"
