- name: Obtain overcloud images
  get_url:
    url="http://rhos-release.virt.bos.redhat.com/puddle-images/latest-8.0-images/{{ item }}.tar" 
    dest="/home/stack/overcloud_images"
  with_items:
    - 'ironic-python-agent'
    - 'overcloud-full'

#TODO(abregman): try to switch back to unarchive at some point unless it still
#                fails unarchive the images tar files.
- name: Unarchive images tar files
  shell: tar xvf /home/stack/overcloud_images/{{ item }} -C /home/stack/overcloud_images
  with_items:
    - 'ironic-python-agent.tar'
    - 'overcloud-full.tar'
