- name: Install the RPM which provides the pre-built overcloud images
  become: yes
  yum:
    name="rhosp-director-images"
    state=present

- name: Extract tar files
  become: yes
  unarchive:
    src="/usr/share/rhosp-director-images/{{ item }}.tar"
    dest="/home/stack/overcloud_images"
    copy=no
    owner=stack
    group=stack
  with_items:
    - 'ironic-python-agent'
    - 'overcloud-full'

- name: Install libguestfs-tools for editing the images
  become: yes
  yum:
    name=libguestfs-tools
    state=present

- name: Inject patches to overcloud full image
  shell: >
    virt-customize --upload /etc/yum.repos.d/rhos-release-10.repo:/etc/yum.repos.d/rhos-release-10.repo -a overcloud-full.qcow2;
    virt-customize --upload /etc/yum.repos.d/rhos-release-rhel-7.3.repo:/etc/yum.repos.d/rhos-release-rhel-7.3.repo -a overcloud-full.qcow2;
    virt-customize -a overcloud-full.qcow2 --install http://download.eng.bos.redhat.com/brewroot/packages/opendaylight/5.2.0/2.el7ost/noarch/opendaylight-5.2.0-2.el7ost.noarch.rpm;
    virt-customize --selinux-relabel --update -a overcloud-full.qcow2
  args:
    chdir: "/home/stack/overcloud_images"
