- name: Obtain overcloud images
  get_url:
    url="http://rhos-release.virt.bos.redhat.com/puddle-images/latest-7.0-images/{{ item }}.tar"
    dest="/home/stack/overcloud_images"
  with_items:
    - 'deploy-ramdisk-ironic'
    - 'discovery-ramdisk'
    - 'overcloud-full'

- name: Extract tar files
  unarchive:
    src="/home/stack/overcloud_images/{{ item }}.tar"
    dest="/home/stack/overcloud_images"
    copy=no
  with_items:
    - 'deploy-ramdisk-ironic'
    - 'discovery-ramdisk'
    - 'overcloud-full'
