- name: Install the RPM which provides the pre-built overcloud images
  become: yes
  yum:
    name="rhosp-director-images"
    state=present

- name: Extract tar files
  become: yes
  unarchive:
    src="/usr/share/rhosp-director-images/{{ item }}.tar"
    dest="/home/stack/overcloud_images"
    copy=no
    owner=stack
    group=stack
  with_items:
    - 'ironic-python-agent'
    - 'overcloud-full'

- name: Check if there are patched RPMs
  stat:
    path="/patched_rpms"
  register: patched_rpms

- name: Install libguestfs-tools for editing the images
  become: yes
  yum:
    name=libguestfs-tools
    state=present
  when: patched_rpms.stat.isdir is defined and patched_rpms.stat.isdir

- name: Inject patches to overcloud full image
  shell: >
    virt-copy-in /patched_rpms / -a overcloud-full.qcow2;
    virt-customize --upload /etc/yum.repos.d/patched_rpms.repo:/etc/yum.repos.d/patched_rpms.repo -a overcloud-full.qcow2;
    virt-customize --selinux-relabel --update -a overcloud-full.qcow2
  args:
    chdir: "/home/stack/overcloud_images"
  when: patched_rpms.stat.isdir
