- name: Install the RPM which provides the pre-built overcloud images
  become: yes
  yum:
    name="rhosp-director-images"
    state=present

- name: Extract tar files
  become: yes
  unarchive:
    src="/usr/share/rhosp-director-images/{{ item }}.tar"
    dest="/home/stack/overcloud_images"
    copy=no
    owner=stack
    group=stack
  with_items:
    - 'ironic-python-agent'
    - 'overcloud-full'

- name: Install libguestfs-tools for editing the images
  become: yes
  yum:
    name=libguestfs-tools
    state=present

- name: Inject patches to overcloud full image
  shell: >
    virt-customize -a overcloud-full.qcow2 --install vim,git,http://cbs.centos.org/repos/nfv7-opendaylight-5-testing/x86_64/os/Packages/opendaylight-5.2.0-1.el7.noarch.rpm
    virt-customize --selinux-relabel --update -a overcloud-full.qcow2
  args:
    chdir: "/home/stack/overcloud_images"
