# Undercloud
# ----------
- name: Prepare undercloud for RHOSP installation
  hosts: undercloud
  vars:
    ansible_ssh_user: root
  roles:
    - { role: setup_undercloud }
    - { role: setup_stack_user }
    - { role: setup_answer_file }
    - { role: setup_undercloud_conf }

- name: Install undercloud
  hosts: undercloud
  vars:
    ansible_ssh_user: stack
  roles:
    - { role: install_undercloud }

- name: Post undercloud installation
  hosts: undercloud
  vars:
    ansible_ssh_user: root
  roles:
    - { role: post_undercloud_install }

# Overcloud
# ---------
