# Undercloud
# ----------
- name: Prepare undercloud for RHOSP 10 installation
  hosts: undercloud
  vars:
    ansible_ssh_user: root
  roles:
    - { role: undercloud/prepare_host }
    - { role: undercloud/setup_stack_user }
    - { role: undercloud/setup_conf_file }

- name: Install undercloud
  hosts: undercloud
  vars:
    ansible_ssh_user: stack
  roles:
    - { role: undercloud/install }

- name: Post undercloud installation
  hosts: undercloud
  vars:
    ansible_ssh_user: root
  roles:
    - { role: undercloud/post_installation }

# Overcloud
# ---------

- name: Install Overcloud
  hosts: undercloud
  vars:
    ansible_ssh_user: stack
  roles:
    - { role: overcloud/setup }
    - { role: overcloud/setup_images }
    - { role: overcloud/register_nodes }
    - { role: overcloud/install }

- name: Post overcloud installation
  hosts: undercloud
  vars:
    ansible_ssh_user: stack
  roles:
    - { role: overcloud/post_installation }

# Localhost
# ---------
- name: Update inventory with overcloud nodes
  hosts: localhost
  roles:
    - { role: overcloud/update_inventory }
