# Undercloud
# ----------
- name: Prepare undercloud for RHOSP installation
  hosts: undercloud
  vars:
    ansible_ssh_user: root
  roles:
    - { role: undercloud/prepare_host }
    - { role: undercloud/setup_stack_user }
    - { role: undercloud/setup_answer_file }
    - { role: undercloud/setup_conf_file }

- name: Install undercloud
  hosts: undercloud
  vars:
    ansible_ssh_user: stack
  roles:
    - { role: undercloud/install }

- name: Post undercloud installation
  hosts: undercloud
  vars:
    ansible_ssh_user: root
  roles:
    - { role: undercloud/post_installation }

# Overcloud
# ---------

- name: Install Overcloud
  hosts: undercloud
  vars:
    ansible_ssh_user: stack
  roles:
    - { role: overcloud/setup }
    - { role: overcloud/register_nodes }
    - { role: overcloud/install }
