- name: resize lvm
  hosts: controller
  become: True
  tasks:
     - command: {{ item }}
       with_items:
          - df -h
          - dd if=/dev/zero of=cinder-volumes2 bs=102400 count=409600
          - df -h
          - losetup /dev/loop3 /var/lib/cinder/cinder-volumes2
          - losetup -l
          - pvdisplay
          - vgdisplay
          - pvcreate /dev/loop3
          - vgextend cinder-volumes /dev/loop3
          - pvdisplay
          - vgdisplay
       args:
          chdir: /var/lib/cinder/

     - name: restart cinder services
       become: yes
       become_method: sudo
       service:
         name="{{ item }}"
         state=restarted
       with_items:
         - "openstack-cinder-api"
         - "openstack-cinder-scheduler"
         - "openstack-cinder-volume"
         - "openstack-cinder-backup"
