- name: Install OVS 2.6
  become: yes
  yum:
    name="{{ item }}"
    state=present
  with_items:
    - "{{ ovs_26 }}"
    - "{{ python_ovs_26 }}"

- name: Install the undercloud
  shell: openstack undercloud install --debug &> /home/stack/undercloud_installation.log
